version: 0.2 
 
#env: 
  #variables: 
     # key: "value" 
     # key: "value" 
  #parameter-store: 
     # key: "value" 
     # key: "value" 
 
phases: 
  install:
    runtime-versions:
        docker: 18     
    commands: 
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo Installing mvn....
      # - wget http://mirror.olnevhost.net/pub/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
      # - tar xzvf apache-maven-3.3.9-bin.tar.gz -C /opt/
      # - export PATH=/opt/apache-maven-3.3.9/bin:$PATH
      - apt update
      - apt install maven
      - mvn -v
      
  pre_build: 
    commands: 
    - echo MVN compile and package
    - mvn package
    
    - echo Logging in to Amazon ECR.... 
    - aws --version
    # update the following line with your own region
    - $(aws ecr get-login --no-include-email --region ap-southeast-2)

  build: 
    commands: 
    - echo Build started on `date` 
    - echo Building the Docker image... 
    # update the following line with the name of your own ECR repository
    - docker build -t demo .
    # update the following line with the URI of your own ECR repository (view the Push Commands in the console)
    - docker tag demo:latest 058510799303.dkr.ecr.ap-southeast-2.amazonaws.com/demo:latest
  post_build: 
    commands: 
    - echo Build completed on `date` 
    - echo pushing to repo
    # update the following line with the URI of your own ECR repository
    - docker push 058510799303.dkr.ecr.ap-southeast-2.amazonaws.com/demo:latest
#artifacts: 
    # - location 
    # - location 
  #discard-paths: yes 
  #base-directory: location 
#cache: 
  #paths: 
    # - paths 
 
